# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:A) Rank B) Name C) Artist D) Upload date E) Views¶

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
import time

In [2]:
# connecting to webdriver
driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")
time.sleep(1)

# Opening Wikipedia webpage
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
time.sleep(2)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/560946248.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [3]:
# Empty list for scraping data
Rank =[]
Name =[]
Artist =[]
Upload_date=[]
Views=[]

In [4]:
# Extracting Rank Via X path
try:
    rank=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
except StaleElementReferenceException:
    Rank.append('NA')

In [5]:
# Extracting Name Via X path
try:
    name=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in name:
        Name.append(i.text)
except NoSuchElementExceptionhElementException:
    Name.append('NA')
except StaleElementReferenceException:
    Name.append('NA')

In [6]:
# Extracting Artist Name Via Xpath
try:
    artist=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist:
        Artist.append(i.text)
except NoSuchElementExceptionhElementException:
    Artist.append('NA')
except StaleElementReferenceException:
    Artist.append('NA')

In [7]:
# Extracting Upload date Via Xpath
try:
    upload_date=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date:
        Upload_date.append(i.text)
except NoSuchElementExceptionhElementException:
    Upload_date.append('NA')
except StaleElementReferenceException:
    Upload_date.append('NA')

In [8]:
# Extracting Views via Xpath
try:
    views=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views:
        Views.append(i.text)
except NoSuchElementExceptionhElementException:
    Views.append('NA')
except StaleElementReferenceException:
    Views.append('NA')

In [9]:
# Dataframe for scrap data
Wiki_YT=pd.DataFrame({'Rank':Rank,'Video Name':Name,'Uploader':Artist,'Views (in Billons)':Views,'Upload Date':Upload_date})
print('\033[1m'+'Most Viewed Video on YouTube from Wikipedia :'+'\033[0m')
Wiki_YT

Most Viewed Video on YouTube from Wikipedia :

,Rank,Video Name,Uploader,Views (in Billons),Upload Date
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,11.40,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.98,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.47,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.81,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.64,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.63,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.90,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.70,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.65,"February 27, 2018"
9,10.,"""Gangnam Style""[24]",Psy,4.55,"July 15, 2012"
10,11.,"""Masha and the Bear – Recipe for Disaster""[29]",Get Movies,4.51,"January 31, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.40,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,4.07,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.76,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.66,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,3.65,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,3.59,"October 22, 2015"
17,18.,"""Axel F""[36]",Crazy Frog,3.52,"June 16, 2009"
18,18.,"""Thinking Out Loud""[37]",Ed Sheeran,3.50,"October 7, 2014"
19,20.,"""Baa Baa Black Sheep""[38]",Cocomelon – Nursery Rhymes,3.38,"June 25, 2018"
20,21.,"""Dark Horse""[39]",Katy Perry,3.35,"February 20, 2014"
21,22.,"""Faded""[40]",Alan Walker,3.34,"December 3, 2015"
22,23.,"""Girls Like You""[41]",Maroon 5,3.33,"May 31, 2018"
23,24.,"""Let Her Go""[42]",Passenger,3.30,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,3.27,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,3.26,"March 22, 2015"
26,27.,"""Perfect""[45]",Ed Sheeran,3.26,"November 9, 2017"
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,3.25,"June 4, 2010"
28,29.,"""Shake It Off""[47]",Taylor Swift,3.21,"August 18, 2014"
29,30.,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.17,"January 26, 2018"

# Q_2 . Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
# You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
c) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [15]:
# connecting to webdriver
driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")
time.sleep(1)

# Opening Wikipedia webpage
url="https://www.bcci.tv/"
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/739407377.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [17]:
# Opening Fixture Tab-
Interational=driver.find_element(By.XPATH,'//*[@id="navigation"]/ul[1]/li[2]/a').click()

In [18]:
#scraping the URL
# scrape match details urls from xpath    
URL= []
link=driver.find_elements(By.XPATH,'//div[@class="js-list"]/a')
for i in link:
    URL.append(i.get_attribute('href'))

In [19]:
# make empty lists
Title=[] 
Series=[]
Place=[]
Date=[]
Time=[]

In [27]:
# Scraping Match title
try:
        title=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
        for i in title:
             Title.append(i.text)
except NoSuchElementException:
        Title.append('-')
        
len(Title)

12

In [28]:
 # Scraping Series Via Xpath
try:
        series=driver.find_elements(By.XPATH,'//div[@class="fixture-card-mid d-flex align-items-center justify-content-between"]')
        for i in series:
            Series.append(i.text)
except NoSuchElementException:
        Series.append('-')     
        
len(Series)

12

In [29]:
# Scraping venue Via Xpath
try:
        place=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
        for i in place:
             Place.append(i.text)
except NoSuchElementException:
        Place.append('NA')
        
len(Place)

18

In [30]:
# Scraping date Via Xpath
try:
        date=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
        for i in date:
            Date.append(i.text)
except NoSuchElementException:
        Date.append('NA')    
        
len(Date)

12

In [31]:
# Scraping Time Via Xpath
try:
        time=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
        for i in time:
            Time.append(i.text)
except NoSuchElementException:
        Time.append('-')
        
len(Time)

12

In [34]:
#creating dataframe
df=pd.DataFrame({})
df['Match Title']=Title[:12]
df['Tournament']=Place[:12]
df['Venue']=Place[:12]
df['Date']=Date[:12]
df['Time']=Time[:12]
df[:12]

,Match Title,Tournament,Venue,Date,Time
0,1st ODI -,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,6 OCT 2022,1:30 PM IST
1,4th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",7 OCT 2022,1:00 PM IST
2,5th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",8 OCT 2022,1:00 PM IST
3,2nd ODI -,"JSCA International Stadium Complex,","JSCA International Stadium Complex,",9 OCT 2022,1:30 PM IST
4,6th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",10 OCT 2022,1:00 PM IST
5,3rd ODI -,"Arun Jaitley Stadium,","Arun Jaitley Stadium,",11 OCT 2022,1:30 PM IST
6,1st ODI -,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,6 OCT 2022,1:30 PM IST
7,4th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",7 OCT 2022,1:00 PM IST
8,5th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",8 OCT 2022,1:00 PM IST
9,2nd ODI -,"JSCA International Stadium Complex,","JSCA International Stadium Complex,",9 OCT 2022,1:30 PM IST
10,6th T20I -,"Sylhet International Cricket Stadium,","Sylhet International Cricket Stadium,",10 OCT 2022,1:00 PM IST
11,3rd ODI -,"Arun Jaitley Stadium,","Arun Jaitley Stadium,",11 OCT 2022,1:30 PM IST

# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:

A) Name
B) Description ###### Note: - From guru99 home page you have to reach to selenium exception handling page through code# 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.You need to find following details:
A) Match title (I.e. 1st ODI) 
B) Series 
C) Place
D) Date 
E) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [2]:
# connecting to webdriver
driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")
time.sleep(1)

# Opening Wikipedia webpage
url='https://www.guru99.com'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_20292/1724923419.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:\Users\User\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [3]:
# Click Selenium Button
Selenium = driver.find_element(By.XPATH,'//*[@id="java_technologies"]/li[3]/a') # click button
try:
    Selenium.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))
time.sleep(3)

In [4]:
# Click selenium exception handling  Button
exception_handling = driver.find_element(By.XPATH,"//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException:  #if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))

In [5]:
name=[]
description=[]
#Scrapping Name
for i in driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]/p/strong'):
    if 'Exception:' in i.text:
        name.append(i.text[3:-1])
for i in driver.find_elements(By.XPATH,'//*[@id="post-1953"]/div/div/p'):
    if 'Exception:' in i.text:
        description.append(i.text.split(' ',2)[2])

In [6]:
Selenium_Exception=pd.DataFrame()
Selenium_Exception['Exception name']=name
Selenium_Exception['Description']=description
Selenium_Exception

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateException,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver doesn’t send...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP at current price (19-20)

D) GSDP at current price (18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code

In [71]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
url='https://www.statisticstimes.com/'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_20292/3343773433.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [72]:
# Creating Empty lists
Rank =[]
State =[]
GDSP_19_20=[]
GDSP_18_19 =[]
Share_18_19 =[]
GDP =[]

In [77]:
# Clicking on India under ecomony section
driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button').click()
India=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/div/a[3]')
try:
    India.click()
except ElementNotInteractableException:
    driver.get(India.get_attribute('href'))
    
time.sleep(2)

In [78]:
# Clicking Indian State GDP
state = driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    state.click()
except ElementNotInteractableException:
    driver.get(state.get_attribute('href'))
time.sleep(2)

In [79]:
# Extracting Rank via Xpath
try:
    rank=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
    
len(Rank)

33

In [80]:
# Extracting state name via Xpath
try:
    state=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append('NA')
    
len(State)

33

In [81]:
# Extracting GDSP 19-20 via Xpath
try:
    gdsp_19_20=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gdsp_19_20:
        GDSP_19_20.append(i.text)
except NoSuchElementException:
    GDSP_19_20.append('NA')
    
len(GDSP_19_20)

33

In [82]:
# Extracting GDSP 18-19 via Xpath
try:
    gdsp_18_19=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gdsp_18_19:
        GDSP_18_19.append(i.text)
except NoSuchElementException:
    GDSP_18_19.append('NA')
    
len(GDSP_18_19)

33

In [85]:
# Extracting share in billons via Xpath
try:
    share=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share:
        Share_18_19.append(i.text)
except NoSuchElementException:
    Share_18_19.append('NA')
    
len(Share_18_19)

66

In [86]:
# Extracting GDP via Xpath
try:
    gdp=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdp:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('NA')
    
len(GDP)

33

In [87]:
# Dataframe for scrap data

df=pd.DataFrame({})
df['Rank']=Rank[:33]
df['State']=State[:33]
df['GDSP 19-20']=GDSP_19_20[:33]
df['GDSP 18-19']=GDSP_18_19[:33]
df['Share 18-19']=Share_18_19[:33]
df['GDP (in Billions)']=GDP[:33]
df[:33]

,Rank,State,GDSP 19-20,GDSP 18-19,Share 18-19,GDP (in Billions)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [171]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
driver.get('https://github.com/trending')
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/3159282213.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [172]:
# Scraping repositories URL
URL= []
link=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a')
for i in link:
    URL.append(i.get_attribute('href'))

In [173]:
# Creating Empty list for Scraping Data
Title=[]
Description=[]
Count =[]
Language =[]

In [174]:
from tqdm import tqdm

In [175]:
# Scraping Repositority Title
Title=[]
try:
    title=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
    for i in title:
        Title.append(i.text)
except NoSuchElementException:
    Title.append('NA')

In [176]:
# Scraping Description
Description=[]
for i in tqdm(URL):
    driver.get(i)
    time.sleep(2)
    try:
        description=driver.find_element(By.XPATH,'//p[@class="f4 my-3"]')
        Description.append(description.text)
    except NoSuchElementException:
        Description.append('NA')
print(len(Description))
Description

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [02:35<00:00,  6.23s/it]

25

["freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
 'Collection of various algorithms in mathematics, machine learning, computer science and physics implemented in C++ for educational purposes.',
 '🚀✨ Help beginners to contribute to open source projects',
 'All Algorithms implemented in Python',
 'CodeEdit App for macOS – Elevate your code editing experience. Open source, free forever.',
 'Turn your audience into a business. Publishing, memberships, subscriptions and newsletters.',
 'SigNoz is an open-source APM. It helps developers monitor their applications & troubleshoot problems, an open-source alternative to DataDog, NewRelic, etc. 🔥 🖥. 👉 Open source Application Performance Monitoring (APM) & Observability tool',
 '🕵️\u200d♂️ Collect a dossier on a person by username from thousands of sites',
 'Recopilación de recursos de ciencias de datos por parte de la comunidad Datos Para Todos',
 'Extensible low-code framework for building business applications. Connect to databases, cloud storages, GraphQL, API endpoints, Airtable, etc and build apps using drag and drop application builder. Built using JavaScript/TypeScript. 🚀',
 "A tiny, efficient fuzzy search that doesn't suck",
 'A cross-platform GUI library for Rust, inspired by Elm',
 'The open-source repo for docs.github.com',
 'protoc plugin to generate polyglot message validators',
 'Une liste de liens permettant de se former aux outils utilisés dans le domaine du Devops',
 'iOS 15.0-15.3.1 tethered checkm8 "jailbreak" (rootless is 15.0-15.7 semi-tethered, no tweaks)',
 '⭐ A fully functional real-time notification center for your web and react apps. The only open-source notifications infrastructure that manages multi-channel content, scheduled notifications, digest engine, user preferences, and delivers Email, SMS, Push and Chat notifications using a single API. ⚡',
 'Odoo. Open Source Apps To Grow Your Business.',
 'Outpainting with Stable Diffusion on an infinite canvas',
 'Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions',
 'Go microservice template for Kubernetes',
 '🤗 Transformers: State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX.',
 'Interactive roadmaps, guides and other educational content to help developers grow in their careers.',
 'A list of Free Software network services and web applications which can be hosted on your own servers',
 'A list of semi to fully remote-friendly companies (jobs) in tech.']

In [177]:
# Scraping Language
Language =[]
for i in tqdm(URL):
    driver.get(i)
    time.sleep(1)
    L =[]
    try:
        lang=driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
        if lang:
            for j in lang:
                L.append(j.text)
        else:
            L.append('NA')
        Language.append(L)
    except NoSuchElementException:
        Language.append('NA')

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [01:18<00:00,  3.12s/it]

In [178]:
# Scraping Contributor count
Count =[]
for i in tqdm(URL):
    driver.get(i)
    time.sleep(1)
    try:
        count=driver.find_element(By.XPATH,"//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Count.append(count.text)
    except NoSuchElementException:
        Count.append('NA')

100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [01:13<00:00,  2.96s/it]

In [179]:
Github=pd.DataFrame({'Title':Title[:25],'Description':Description,
                'Contributors_count':Count,'Language_used':Language})
print('\033[1m'+'GitHub Trending Repository :'+'\033[0m')
Github

GitHub Trending Repository :

,Title,Description,Contributors_count,Language_used
0,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,553","[TypeScript, JavaScript, CSS, Shell, Dockerfil..."
1,TheAlgorithms / C-Plus-Plus,Collection of various algorithms in mathematic...,280,"[C++, CMake]"
2,firstcontributions / first-contributions,🚀✨ Help beginners to contribute to open source...,"4,005",[NA]
3,TheAlgorithms / Python,All Algorithms implemented in Python,845,[Python]
4,CodeEditApp / CodeEdit,CodeEdit App for macOS – Elevate your code edi...,71,[Swift]
5,TryGhost / Ghost,Turn your audience into a business. Publishing...,414,"[JavaScript, Handlebars, CSS, HTML, XSLT]"
6,SigNoz / signoz,SigNoz is an open-source APM. It helps develop...,69,"[TypeScript, Go, Shell, JavaScript, Makefile, ..."
7,soxoj / maigret,🕵️‍♂️ Collect a dossier on a person by usernam...,19,"[Python, HTML, Smarty, Jupyter Notebook, Makef..."
8,FernandaCader / recursos-datos,Recopilación de recursos de ciencias de datos ...,NA,[NA]
9,ToolJet / ToolJet,Extensible low-code framework for building bus...,217,"[JavaScript, TypeScript, SCSS, HTML, Shell, EJS]"
10,leeoniya / uFuzzy,"A tiny, efficient fuzzy search that doesn't suck",2,[JavaScript]
11,iced-rs / iced,"A cross-platform GUI library for Rust, inspire...",126,"[Rust, GLSL]"
12,github / docs,The open-source repo for docs.github.com,"1,465","[JavaScript, TypeScript]"
13,bufbuild / protoc-gen-validate,protoc plugin to generate polyglot message val...,99,"[Go, Java, Starlark, Python, C++, Makefile]"
14,stephrobert / awesome-french-devops,Une liste de liens permettant de se former aux...,15,[NA]
15,palera1n / palera1n,"iOS 15.0-15.3.1 tethered checkm8 ""jailbreak"" (...",7,[Shell]
16,novuhq / novu,⭐ A fully functional real-time notification ce...,118,"[TypeScript, JavaScript, HTML, Handlebars, Doc..."
17,odoo / odoo,Odoo. Open Source Apps To Grow Your Business.,"1,474","[JavaScript, Python, SCSS, CSS, HTML, Shell]"
18,lkwq007 / stablediffusion-infinity,Outpainting with Stable Diffusion on an infini...,3,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
19,nvm-sh / nvm,Node Version Manager - POSIX-compliant bash sc...,317,"[Shell, Makefile]"
20,stefanprodan / podinfo,Go microservice template for Kubernetes,35,"[Go, CUE, HTML, Makefile, Shell, Smarty, Docke..."
21,huggingface / transformers,🤗 Transformers: State-of-the-art Machine Learn...,"1,428","[Python, Cuda, Shell, Dockerfile, C++, C]"
22,kamranahmedse / developer-roadmap,"Interactive roadmaps, guides and other educati...",346,"[TypeScript, JavaScript, Shell]"
23,awesome-selfhosted / awesome-selfhosted,A list of Free Software network services and w...,"1,125","[JavaScript, Makefile, Python, Ruby]"
24,remoteintech / remote-jobs,A list of semi to fully remote-friendly compan...,666,"[JavaScript, HTML, CSS, Shell]"

# 6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/ You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [42]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
url='https://www.billboard.com/charts/hot-100/'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_20292/246709662.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [43]:
# Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [44]:
# Scraping name
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    Song_Name.append(i.text)
len(Song_Name)

100

In [45]:
#Scrappin Artist name 1 st one
Artist_Name.append(driver.find_element(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)

In [46]:
#Remainig Artist Name
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
Artist_Name.extend([i.text for i in artistTag])

In [47]:
#Scapping Rank
rank=[]
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])

In [48]:
#Scrappin Artist name 1 st one
Artist_Name.append(driver.find_element(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)

In [49]:
#Remaining RAnk
Rank=[]
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

In [51]:
#Scapping Rank
rank=[]
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])

In [57]:
#Remaining RAnk
Rank=[]
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

In [54]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [55]:
# slicing as per requirement
lastweekpos=Rank[0::3]
lastweekpos.insert(0,rank[0])
peakPos=Rank[1::3]
peakPos.insert(0,rank[1])
weeksonBoard=Rank[2::3]
weeksonBoard.insert(0,rank[2])

In [58]:
# Create Dataframe
df=pd.DataFrame()
df['SongName']=Song_Name[0:100]
df['ArtistName']=Artist_Name[0:100]
df['Last Week']=lastweekpos[0:100]
df["PeekPosition"]=peakPos[0:100]
df['Weeks On board']=weeksonBoard[0:100]
df

,SongName,ArtistName,Last Week,PeekPosition,Weeks On board
0,Bad Habit\nSteve Lacy\n2\n1\n13,Steve Lacy,2,1,13
1,As It Was\nHarry Styles\n1\n1\n26,Harry Styles,1,1,26
2,Unholy\nSam Smith & Kim Petras\n-\n3\n1,Sam Smith & Kim Petras,-,3,1
3,I Like You (A Happier Song)\nPost Malone Featu...,Post Malone Featuring Doja Cat,3,3,17
4,Sunroof\nNicky Youre & dazy\n4\n4\n18,Nicky Youre & dazy,4,4,18
...,...,...,...,...,...
95,Blow\nMoneybagg Yo\n-\n96\n1,Moneybagg Yo,80,80,4
96,World's Smallest Violin\nAJR\n-\n97\n1,AJR,,,
97,Oklahoma Smoke Show\nZach Bryan\n-\n98\n1,Zach Bryan,87,76,6
98,No Se Va\nGrupo Frontera\n-\n99\n1,Grupo Frontera,,,
99,Down Home\nJimmie Allen\n-\n100\n1,Jimmie Allen,92,75,10

# 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [102]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Getting the webpage of mentioned url 
url = "https://www.naukri.com/"
driver.get(url)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/2870424218.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [103]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [104]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element(By.XPATH,"/html/body/div[1]/div[6]/div/div/div[1]/div/div/div/input") 
search.send_keys("Data science ")           
btn = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[6]').click()     
time.sleep(3)

In [105]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [106]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//div[@class='job-description fs12 grey-text']"):
    Name.append(i.text)
time.sleep(3)

#Scraping data of Designation
for i in driver.find_elements(By.XPATH,"//a[@class='title fw500 ellipsis']"):
    Designation.append(i.text)
    
#Scraping data of company name
for i in driver.find_elements(By.XPATH,"//a[@class='subTitle ellipsis fleft']"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis fleft']"):
    Location.append(i.text)
time.sleep(3)

#Scraping data of skills
for i in driver.find_elements(By.XPATH,"//ul[@class='tags has-description']"):
    Skills.append(i.text)

In [108]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[0:19]
Naukri['Designation'] = Designation[0:19]
Naukri['Company'] = Company[0:19]
Naukri['Location'] = Location[0:19]
Naukri['Skills']=Skills[0:19]
Naukri

,Name,Designation,Company,Location,Skills
0,Bachelors in STEM Must have 5+ years experienc...,Data Analyst - Data Science,Altigreen,Data Science & Analytics,Data analysis\nBusiness Analyst\ndata science\...
1,"4+ years of relevant industry experience, or a...",Data Storytelling / Visualization Role - Data ...,Indiainfoline,Engineering - Software & QA,visualization\ninteractive dashboards\nAnalyti...
2,Predictive Analytics Well versed with AI and M...,Hiring For Data Science role (NLP) - Max 30 Da...,Genpact,"Customer Success, Service & Operations",Speech Analytics\nText Analytics\nNatural Lang...
3,Roles and Responsibilities Urgently Required S...,Data Science Analyst (From FMCG Ind.)and Sales...,H K Jewels,Other,SAP\nData Management\nData Analysis\nData Anal...
4,Work from home flexible but individuals must b...,Senior Data Science Manager,Inspire Analytics,WFH during Covid,python\nUnix\nArchitectural Patterns\nData Cle...
5,Requirements: - Bachelor s/ Masters degree in ...,Senior Director & Head-Data Science & Analytics,Vertex Corporate Services,Remote,Data Science\nC/C++\nJava\nHive\ndesign\ninter...
6,Skill required: Data Science - Python Programm...,Senior Analyst-Data Science,Accenture,Bangalore/Bengaluru,Publishing\nArtificial Intelligence\nConsultin...
7,"Own and design statistical model, evaluate dif...",Data Science Lead - Forecasting,Cargill,Delhi / NCR,Data analysis\ndata science\nMachine learning\...
8,Centralize and accelerate RD prototyping Liais...,"Senior Specialist - Data Science, ESG",Marsh &amp;amp; McLennan Companies,Gurgaon/Gurugram,data science\nConsulting\nJavascript\nData min...
9,Requirements: Responsible for taking up day-to...,ACN - Applied Intelligence - CC - Data Science...,Accenture,0-3 Lakhs,Data analysis\nAnalytical\nConsulting\nAnalyti...
10,"Develop, execute, and maintain lending valuati...",Senior Investment Risk Specialist - Data Science,Wells Fargo,3-6 Lakhs,remediation\nBloomberg\nQuantitative research\...
11,5 years of experience in delivering scalable m...,Senior Data Science Manager,Inspire Careers,6-10 Lakhs,Data analysis\ndata science\nDebugging\nMachin...
12,You should be self-driven and motivated with t...,AI & Data Science Senior Engineer,Wasoko,10-15 Lakhs,Mining\nMachine learning\nAgile\nData structur...
13,Roles and Responsibilities As a HR Decision Sc...,Data Science Analyst,Search Advisers Services ( GUJ ) Pvt. Ltd.,Foreign MNC,data science\nHR Topics\nModelling\nGlobal Peo...
14,Roles and Responsibilities As a HR Decision Sc...,Data Science Analyst,Search Advisers Services ( GUJ ) Pvt. Ltd.,Corporate,data science\nHR Topics\nModelling\nGlobal Peo...
15,Requirements: - Bachelor s/ Masters degree in ...,Senior Director & Head-Data Science & Analytic...,Vertex Corporate Services,Indian MNC,Data Science\nAnalytics\nJava\nR\nHive\nC++\nC...
16,in Computer scienceInformation Technology ECE ...,Senior Analyst & AI Lead - Data Science,Huquo Consulting Pvt. Ltd,Startup,Artificial Intelligence\nMachine Learning\nDat...
17,in Computer scienceInformation Technology ECE ...,Senior Analyst & AI Lead - Data Science,Huquo Consulting Pvt. Ltd,Business Intelligence & Analytics,Data Science\nIT Skills\nPython\nTesting\nMach...
18,in Computer scienceInformation Technology ECE ...,Senior Analyst & AI Lead - Data Science,Huquo Consulting Pvt. Ltd,Data Science & Machine Learning,Python\nIT Skills\nTesting\nData Science\nMach...

# Q_8_Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [111]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/2856894683.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [112]:
# Creating Empty Lists
Book =[]
Author =[]
Volumes_sold =[]
Publisher =[]
Genre =[]

In [125]:
# Scraping Book name
try:
    book=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book:
        Book.append(i.text)
except NoSuchElementException:
    Book.append('NA')
    
    
len(Book)

200

In [120]:
# Scraping Book author's via Xpath
try:
    author=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in author:
        Author.append(i.text)
except NoSuchElementException:
    Author.append('NA')
    
len(Author)

200

In [121]:
# Scraping Volumes sold via Xpath
try:
    sold=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in sold:
        Volumes_sold.append(i.text)
except NoSuchElementException:
    Volumes_sold.append('NA')

    
len(Volumes_sold)

200

In [122]:
# Scraping publisher via xPath
try:
    publisher=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in publisher:
        Publisher.append(i.text)
except NoSuchElementException:
    Publisher.append('NA')
    
    
len(Publisher)

200

In [126]:
# Scraping Genre via Xpath
try:
    genre=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')
    
    
len(Genre)

500

In [128]:
# Creating dataframe for scraped data
Top_Book=pd.DataFrame({})
Top_Book['Book Title'] = Book[0:200]
Top_Book['Author Name'] = Author[0:200]
Top_Book['Volumes sold'] = Volumes_sold[0:200]
Top_Book['Publisher'] = Publisher[0:2000]
Top_Book['Genre']=Genre[0:200]
Top_Book

,Book Title,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
195,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
196,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
197,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
198,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
199,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [145]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_18304/2113668778.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [146]:
# Creating Empty List
Name =[]
Year_Span=[]
Genre =[]
Run_Time =[]
Ratings =[]
Votes =[]

In [147]:
# Creating Empty List
Name =[]
Year_Span=[]
Genre =[]
Run_Time =[]
Ratings =[]
Votes =[]

In [148]:
# Scraping Year span via Xpath
try:
    year=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/span[2]")
    for i in year:
        Year_Span.append(i.text)
except NoSuchElementException:
    Year_Span.append('NA')

    
len(Year_Span)

100

In [149]:
# Scraping Genre via Xpath
try:
    genre=driver.find_elements(By.XPATH,"//span[@class='genre']")
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')
    
    
len(Genre)

100

In [150]:
# Scraping RunTime via Xpath
try:
    runtime=driver.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in runtime:
        Run_Time.append(i.text)
except NoSuchElementException:
    Run_Time.append('NA')
    
    
len(Run_Time)

100

In [151]:
# Scraping Ratings via Xpath
try:
    ratings=driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]")
    for i in ratings:
        Ratings.append(i.text)
except NoSuchElementException:
    Ratings.append('NA')
    
    
len(Ratings)

100

In [152]:
# Scraping Votes via Xpath
try:
    votes=driver.find_elements(By.XPATH,"//span[@name='nv']")
    for i in votes:
        Votes.append(i.text)
except NoSuchElementException:
    Votes.append('NA')
    
    
len(Votes)

100

In [153]:
# Scraping Name via Xpath
try:
    name=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('NA')
    
len(Name)

100

In [154]:
#creating dataframe
IMDB_TV=pd.DataFrame({"Name":Name,
                "Year Span":Year_Span,
                "Genre":Genre,
                "Run Time":Run_Time,
                "Ratings":Ratings,
                "Votes":Votes})
print('\033[1m'+'Top 100 most watched tv shows of all time IMDB :'+'\033[0m')
IMDB_TV

Top 100 most watched tv shows of all time IMDB :

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,061,434"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,154,985"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"972,340"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"289,910"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"249,336"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,692"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,743"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"195,519"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,153"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"238,143"

# Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

import selenium

In [59]:
# connecting to webdriver
driver=webdriver.Chrome(r'C:\chromedriver.exe')
time.sleep(1)

# Opening Wikipedia webpage
url='https://archive.ics.uci.edu/'
driver.get(url)
time.sleep(1)

C:\Users\User\AppData\Local\Temp/ipykernel_20292/2281512333.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r'C:\chromedriver.exe')

In [60]:
# Clicking on all datasets links
dataset=driver.find_element(By.XPATH,"//a[@href='datasets.php']")
dataset.click()
time.sleep(1)

In [61]:
# Creating empty lists
Dataset =[]
Data_Type =[]
Task =[]
Attribute_Type =[]
No_of_Instances =[]
No_of_Attribute =[]
Year =[]

In [62]:
# Scraping DataSet Name via Xpath
from tqdm import tqdm
try:
    dataset=driver.find_elements(By.XPATH,"//p[@class='normal']/b/a")
    for i in tqdm(dataset):
        Dataset.append(i.text)
        time.sleep(0.15)
except NoSuchElementException:
    Dataset.append('NA')

100%|████████████████████████████████████████████████████████████████████████████████| 622/622 [02:50<00:00,  3.66it/s]

In [63]:
# Scraping Data Type via Xpath
try:
    Type=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in Type[1:]:
        Data_Type.append(i.text)
except NoSuchElementException:
    Data_Type.append('NA')

In [64]:
# Scraping Task via Xpath
try:
    task=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('NA')

In [65]:
# Scraping Attribute_Type via Xpath
try:
    attribute_Type=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
    for i in attribute_Type[1:]:
        Attribute_Type.append(i.text)
except NoSuchElementException:
    Attribute_Type.append('NA')

In [14]:
# Scraping No_of_Instances via Xpath
try:
    no_of_Instances=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
    for i in no_of_Instances[1:]:
        No_of_Instances.append(i.text)
except NoSuchElementException:
    No_of_Instances.append('NA')

In [15]:
# Scraping No_of_Attribute via Xpath
try:
    no_of_Attribute=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
    for i in no_of_Attribute[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('NA')

In [16]:
# Scraping Year via Xpath
try:
    year=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]')
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('NA')

In [17]:
# Creating Data Frame for UCI Dataset
UCI_Dataset=pd.DataFrame({'DataSet Title':Dataset,
                'Data Type':Data_Type,
                'Task':Task,
                'Attribute Type':Attribute_Type,
                'No of Instances':No_of_Instances,
                'No of Attribute':No_of_Attribute,
                'Year':Year})
print('\033[1m'+' UCI Machine Learning Dataset:'+'\033[0m')
UCI_Dataset

 UCI Machine Learning Dataset:

,DataSet Title,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021